version: "3"
services:
  dotnet-webapi:
    image: fordperfect/dotnet-webapi
    ports:
      - "5000:80"
    environment:
      - OltpEndpoint=${OltpEndpoint}
    logging:
      driver: loki
      options:
        loki-url: ${LOKI_URL}
  grafana-agent:
    image: grafana/agent:latest
    command: "-config.file=/etc/agent-config.yaml"
    volumes:
      - ./agent-config.yaml:/etc/agent-config.yaml
